### ISSUE TITLE
Grid detecting images

### ISSUE THREAD

**Issue by kaiguy920** [kaiguy920/Game-Project#1]
I have my board set to a grid & have moving pieces set to the grid. To assign moves, I've created div's associated with the grid. Due to that, the pieces aren't registering as taking up space in the divs to prevent other pieces to the same spot. I've been spinning out on a resolution for a few hours now.

```html
<div id="imgContainer">
        <img draggable="true" id="navyDump" class="cars" src="images/navyDump.gif">
        <img draggable="true" id="greenCar" class="cars" src="images/greenCar.gif">
        <img draggable="true" id="lightBlueCar" class="cars" src="images/lightBlueCar.gif">
        <img draggable="true" id="orangeCar" class="cars" src="images/orangeCar.gif">
        <img draggable="true" id="purpleDump" class="cars" src="images/purpleDump.gif">
        <img draggable="true" id="redCar" class="cars" src="images/redCar.gif">
        <img draggable="true" id="tealDump" class="cars" src="images/tealDump.gif">
        <img draggable="true" id="yellowDump" class="cars" src="images/yellowDump.gif">

        <div id="r2c2" class="squares"></div>
        <div id="r2c3" class="squares"></div>
        <div id="r2c4" class="squares"></div>
        <div id="r2c5" class="squares"></div>
        <div id="r2c6" class="squares"></div>
        <div id="r2c7" class="squares"></div>

        <div id="r3c2" class="squares"></div>
        <div id="r3c3" class="squares"></div>
        <div id="r3c4" class="squares"></div>
        <div id="r3c5" class="squares"></div>
        <div id="r3c6" class="squares"></div>
        <div id="r3c7" class="squares"></div>

        <div id="r4c2" class="squares"></div>
        <div id="r4c3" class="squares"></div>
        <div id="r4c4" class="squares"></div>
        <div id="r4c5" class="squares"></div>
        <div id="r4c6" class="squares"></div>
        <div id="r4c7" class="squares"></div>
        <div id="r4c8" class="squares"></div>

        <div id="r5c2" class="squares"></div>
        <div id="r5c3" class="squares"></div>
        <div id="r5c4" class="squares"></div>
        <div id="r5c5" class="squares"></div>
        <div id="r5c6" class="squares"></div>
        <div id="r5c7" class="squares"></div>

        <div id="r6c2" class="squares"></div>
        <div id="r6c3" class="squares"></div>
        <div id="r6c4" class="squares"></div>
        <div id="r6c5" class="squares"></div>
        <div id="r6c6" class="squares"></div>
        <div id="r6c7" class="squares"></div>

        <div id="r7c2" class="squares"></div>
        <div id="r7c3" class="squares"></div>
        <div id="r7c4" class="squares"></div>
        <div id="r7c5" class="squares"></div>
        <div id="r7c6" class="squares"></div>
        <div id="r7c7" class="squares"></div>
    </div>

```
```css
#imgContainer {
    background-image: url(../images/board.gif); 
    background-repeat: no-repeat;
    background-position: center center;
    /* background-size: cover; */
    width: 600px;
    height: 600px;
    display: grid;
    grid-template-rows: 13.25% 12% 12% 12% 12% 12% 12% 14.75%;
    grid-template-columns: 14% 12% 12% 12% 12% 12% 12% 14%;
}

```
